name: Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Zip Theme
        run: yarn blog:zip
      - uses: actions/checkout@master
      - name: Deploy Ghost Theme
        run: |
          # Token generation based on https://github.com/TryGhost/Ghost-SDK/blob/0b4db41bbe944bf6fe03e764de58be856fb5dc34/packages/admin-api/lib/token.js
          TOKEN=`node -e "const [keyid, secret] = '$API_KEY'.split(':'); console.log(require('./node_modules/jsonwebtoken/index.js').sign({}, Buffer.from(secret, 'hex'), {keyid, algorithm: 'HS256', expiresIn: '5m', audience: '/v3/admin/'}));"`
          curl -H "Authorization: Ghost $TOKEN" -F "file=@./vikas-potluri-theme.zip" $API_BASE/ghost/api/v3/admin/themes/upload/ --silent > /dev/null
        env:
          API_BASE: ${{ secrets.GHOST_ADMIN_API_URL }}
          API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
